tickets = [
    # BILLING (17 tickets)
    ("I was charged twice for my subscription this month", "billing"),
    ("Can I get a refund for the unused portion of my plan?", "billing"),
    ("My credit card was declined but I have sufficient funds", "billing"),
    ("I need to update my payment method to a new card", "billing"),
    ("The price increased without any notification", "billing"),
    ("I see an unauthorized charge on my account", "billing"),
    ("Can you explain the charges on my latest invoice?", "billing"),
    ("I cancelled but was still charged for next month", "billing"),
    ("Is there a discount for annual billing?", "billing"),
    ("My promo code isn't applying the discount correctly", "billing"),
    ("I need a receipt for my last three payments", "billing"),
    ("Why was I charged a late fee?", "billing"),
    ("Can I split my payment across two credit cards?", "billing"),
    ("The auto-renewal charged the wrong amount", "billing"),
    ("I need to dispute a charge from last month", "billing"),
    ("When will my refund be processed?", "billing"),
    ("I was charged sales tax but my state is tax-exempt", "billing"),

    # TECHNICAL (17 tickets)
    ("The app crashes every time I try to upload a file", "technical"),
    ("I'm getting a 500 error when accessing the dashboard", "technical"),
    ("The search function returns no results even for exact matches", "technical"),
    ("My data export is missing several columns", "technical"),
    ("The mobile app won't sync with the desktop version", "technical"),
    ("Page load times have been extremely slow this week", "technical"),
    ("The API is returning malformed JSON responses", "technical"),
    ("I can't connect my third-party integration", "technical"),
    ("The notification system isn't sending email alerts", "technical"),
    ("Two-factor authentication codes aren't being accepted", "technical"),
    ("The file preview feature shows a blank screen", "technical"),
    ("My scheduled reports aren't generating automatically", "technical"),
    ("The drag-and-drop feature stopped working after the update", "technical"),
    ("I'm getting timeout errors on large database queries", "technical"),
    ("The webhook endpoint isn't receiving any payloads", "technical"),
    ("Charts and graphs aren't rendering in the analytics tab", "technical"),
    ("The bulk import tool fails silently with no error message", "technical"),

    # ACCOUNT (16 tickets)
    ("I forgot my password and the reset email never arrives", "account"),
    ("I need to change the email address on my account", "account"),
    ("How do I add another user to my team account?", "account"),
    ("My account was locked after too many login attempts", "account"),
    ("I want to upgrade from the free plan to professional", "account"),
    ("Can I transfer ownership of my account to a colleague?", "account"),
    ("I need to delete my account and all associated data", "account"),
    ("How do I enable single sign-on for my organization?", "account"),
    ("My profile picture won't update", "account"),
    ("I can't access the admin panel even though I'm an admin", "account"),
    ("How do I merge two duplicate accounts?", "account"),
    ("I need to change my username", "account"),
    ("Can I temporarily deactivate my account?", "account"),
    ("My account permissions seem wrong after the migration", "account"),
    ("How do I set up role-based access for my team?", "account"),
    ("I need to export all my account data before closing it", "account"),

    # SHIPPING (16 tickets)
    ("My order hasn't arrived and it's been two weeks", "shipping"),
    ("The tracking number shows no movement for 5 days", "shipping"),
    ("I received the wrong item in my package", "shipping"),
    ("Can I change my delivery address after placing the order?", "shipping"),
    ("The package arrived damaged", "shipping"),
    ("Do you offer express shipping options?", "shipping"),
    ("I need to return an item — how do I get a shipping label?", "shipping"),
    ("My order was marked delivered but I never received it", "shipping"),
    ("Can I pick up my order from a local facility instead?", "shipping"),
    ("The shipping cost seems too high for a small item", "shipping"),
    ("I need to ship to an international address", "shipping"),
    ("My package was returned to sender — why?", "shipping"),
    ("How long does standard shipping take?", "shipping"),
    ("I want to consolidate multiple orders into one shipment", "shipping"),
    ("The delivery driver left my package in the rain", "shipping"),
    ("Can I schedule a specific delivery time window?", "shipping"),
]